version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: "04:00"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 5
    groups:
      gradle-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: "04:15"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 3
    groups:
      container-bases:
        patterns:
          - "*"
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: "04:30"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 5
    groups:
      actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps
