{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubert.fullname" . }}
  labels:
    {{- include "kubert.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    resourceNames:
      - {{ include "kubert.fullname" . }}
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubert.fullname" . }}
  labels:
    {{- include "kubert.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubert.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubert.fullname" . }}
{{- end }}
